### ISSUE TITLE
OBS Multiview

### ISSUE THREAD

**Issue by mzlt** [Off-World-Live/obs-spout2-plugin#15] opened 2021-01-25 18:01 UTC
**Describe the bug**
If I create 3 scenes in OBS, each with one instance of spout capture as a source I can only see the current active one of those in OBS Multiview (they seem to fade out from one to the other as I click through between the scenes in Multiview)

**To Reproduce**
1. Open OBS and create 3 scenes
2. In each Scene add one source: Spout Capture and choose a different spout sender of each one
3. Press View->Multiview (either Full Screen or Windowed)

**Expected behavior**
All three scenes should be visible in the Multiview

Log: 
[2021-01-25 17-29-23.txt](https://github.com/Off-World-Live/obs-spout2-source-plugin/files/5868334/2021-01-25.17-29-23.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/26505067/105745713-7e7e2100-5f36-11eb-84e8-82a02c7441a3.png)

**About the Software:**
 - OBS Version 26.1.0, 64 bit windows 
 - OBS Spout 2 Source Plugin Version [not sure where to find that info]

**About Your Machine :**
 - OS: Windows 10 
 - GPU Nvidia RTX 2070
 - NVidia Driver Version 461.09
 - RAM 32GB
 - Machine Type laptop
 - Battery Mode [plugged in

**Comment by LexyVFX** [comment] 2021-03-17 19:21
For what it's worth, I was able to reproduce this issue with OBS using Resolume as a texture source and also found a workaround with the attached screenshots. 

It appears OBS is simply aggressively closing sources that aren't active. Media Sources have some settings for whether media should be kept open by force or not which doesn't translate to Spout Sources currently. I found by simply adding each source to all scenes and set to visible, but with the extras beneath an opaque background plate of some kind, it keeps the spout feeds open. It makes the scenes for each camera a little more cluttered but it does indeed get things working.

Reproducing the problem in two parts:
![image_2021-03-17_13-06-49](https://user-images.githubusercontent.com/4960608/111525490-4e2b5580-8723-11eb-979a-e770eb1dea75.png)

![image_2021-03-17_13-07-52](https://user-images.githubusercontent.com/4960608/111525492-4ec3ec00-8723-11eb-845a-8d8143a0ded9.png)

Applying a workaround until such a time the Source closing behavior can be tweaked:
![image_2021-03-17_13-11-53](https://user-images.githubusercontent.com/4960608/111525656-77e47c80-8723-11eb-93ea-ced14587c0cb.png)

![image_2021-03-17_13-12-08](https://user-images.githubusercontent.com/4960608/111525661-787d1300-8723-11eb-8b78-6884f0861dc3.png)

**Comment by ItsFlo** [comment] 2021-11-05 23:31
This and #17 can be fixed by changing `obs_source_active` in https://github.com/Off-World-Live/obs-spout2-plugin/blob/651d58e51b88be995b6d4d553204cfaebcde5ba9/source/win-spout-source.cpp#L360 to `obs_source_showing`.
I tested this localy. In `spout_source` the attribute `active` becomes useless then though, because the video_render function only gets called when the source is showing. So it could also just be removed but I don´t know if there are any other intended uses for it.

**Comment by shugen002** [comment] 2021-11-06 11:01
> This and #17 can be fixed by changing `obs_source_active` in
> 
> https://github.com/Off-World-Live/obs-spout2-plugin/blob/651d58e51b88be995b6d4d553204cfaebcde5ba9/source/win-spout-source.cpp#L360
> 
> to `obs_source_showing`.
> I tested this localy. In `spout_source` the attribute `active` becomes useless then though, because the video_render function only gets called when the source is showing. So it could also just be removed but I don´t know if there are any other intended uses for it.

set an option maybe better?

**Closed** 2022-01-05 14:43 UTC
Labels: bug
